# Generated by Django 5.2.8 on 2025-12-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='membership_id',
        ),
    ]
