# Generated by Django 5.2.8 on 2025-12-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_memberprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='scheduler.trainerprofile'),
        ),
    ]
